### ISSUE TITLE
Connection reset by peer: socket write error

### ISSUE THREAD

**Issue by Migushthe2nd** [digableinc/tinfoil#14]
While trying to download from my google-drive-to-ftp-adapter the files won't download. The ftp server logs the following: https://paste.ofcode.org/aVPhzJ55akbsx32kf8cNTz
I can download from it fine via my PC though.
Tinfoil itself logs 
"Unknown NCA magic (decryption failed?): ********
Could not open cnmt nca"
This probably has something to do with how Tinfoil tries to _get_ files. I'm using Tinfoil version 0.95

**Comment by Migushthe2nd** [comment]
This is coused by Tinfoil *apparantly* closing the connection (for a short time) when the request just finished at the server. The same error message as in the above paste appears in the server when I discard a download on my pc.

**Comment by blawar** [comment]
Tinfoil sends lots of small requests to the server to read small bits of the file all over.  It closes the connection once its read the small amount of data that it wants.  It is seeking all over the file, so it doesnt have to download the entire file to save you bandwidth and time.

Unknown NCA magic means either your keys.txt is wrong, or the FTP returned incorrect data.  The issue may simply be that your google drive FTP connector does not support ranged requests properly.

Can you confirm that your FTP works with a normal FTP server?

**Comment by Migushthe2nd** [comment]
Ok I'll update my keys.txt. The google drive adapter also has to download part of the file before it can be read via ftp. I think the adapter hasn't downloaded enough of the file for Tinfoil to read it because, as you said, is sends lots of small requests. Maybe Tinfoil closes the connection while the adapter is still downloading part of the file to make it accessible. I changed a few things in the server and Tinfoil still logs an error, but a different one:
network error: transfer closed with 1048576 bytes remaining to read
Failed to read pfs0 header

**Comment by blawar** [comment]
It cant be your keys.txt if it installs fine locally.

Tinfoil has read timeouts for network installs, I think it will wait 30 seconds max and then time out.  I could expose these as variables for people to tweak.

**Comment by Migushthe2nd** [comment]
Version 0.971 still has the problem 
"network error: transfer closed with 1048576 bytes remaining to read
Failed to read pfs0 header"
Small files (120kb) do work.

**Comment by blawar** [comment]
So the issue is only with small files?  large files work fine?

**Comment by Migushthe2nd** [comment]
No only bigger files fail. I've tried files around 120kb and those work fine.

**Comment by leorod199** [comment]
Same problem here :(

`https://i.postimg.cc/gJcdQ5Dk/IMG-20181231-000401.jpg`

This application "https://gbatemp.net/threads/lgma-use-google-drive-with-dz-to-download-your-games.521996/" works to read and install the games, but has a bug that does not recognize all google drive games.

Thank you ;)

**Comment by blawar** [comment]
try using rclone serve ftp.
