### ISSUE TITLE
Dz crashing on 4.0.1

### ISSUE THREAD

**Issue by hax4dazy** [digableinc/tinfoil#16]
I have followed the guide but dz just wont start on my 4.0.1 atmosphere cfw switch. Any help for this? thanks.

**Comment by blawar** [comment]
Hello,

I assume you downloaded 0.97.  There was a bug where that did not work on Atmosphere, and we quickly released 0.971 to fix this issue.  Please upgrade and try again.

**Comment by hax4dazy** [comment]
Hmm i tried that but it still crashes my console

**Comment by hax4dazy** [comment]
Ok i updated to 6.1.0 and now it works.

**Comment by blawar** [comment]
We do not officially support 4.x, only 5.x+
