### ISSUE TITLE
Timing out before loading full lists

### ISSUE THREAD

**Issue by 420pope** [digableinc/tinfoil#20]
First off
Fuck the h8ter children, this app is the shit giggle mctitz and allows me to easily access my personal eShop.

However, the network time out is not playing nice with my full cdn backup.
Often times I have to refresh multiple times; which requires multiple application restarts, to pull the full list from my server.

**Comment by blawar** [comment]
I will add an option to modify timeout value in next commit to master, probably tonight.

**Comment by blawar** [comment]
Sorry for the delay, master has an option for setting the timeout.  give it a shot (I havent tested it).
