### ISSUE TITLE
New added titles dont appears

### ISSUE THREAD

**Issue by langostaman** [digableinc/tinfoil#21]
Hi, frist...thanks for your job and sorry about my english...
I have an vps and connect tinfoil with this by ftp.
When i add a new game this not appears y the game section.
But if i go to the file explorer yes...and i can install from here.
I dont know if this is an issue or my fault...
Is his concerned about the db file?
Thanks

**Comment by blawar** [comment]
Hello,

make sure the file has [titleid] in the name, like "1-2-Switch[01000320000CC000][US][v0].nsp"

**Comment by langostaman** [comment]
Thanks!!!
This is the problem....is posible that in older versions of DZ dont happen this? i rememeber install games without this format of name...
Perfect....one last thing... can u tell me where i can find the number for each game?
I download some games without the number.
Really thanks again!!!
Sorry for open an issue that really isent..

**Comment by blawar** [comment]
You can find the title id's in here:

https://github.com/digableinc/tinfoil/tree/master/db

**Comment by langostaman** [comment]
Im so stupid.....jajaja
Thanks again and really good, good job
