### ISSUE TITLE
Can't install new update nsp

### ISSUE THREAD

**Issue by riggzh** [digableinc/tinfoil#22]
old version has installed list , but new version don't have it 

i installed [01002cc003fe6800][v65536].nsp 
today i pull an new update [01002cc003fe6800][v131072].nsp 

but i can't found it. 

finally i uninstall the old update, restart dz. i can found the new update

**Comment by blawar** [comment]
this might be a bug with how the versions are parsed.  I will look into it and try to reproduce the issue on my end.  Thank you for your report!  I will check back when I have more info.

**Comment by blawar** [comment]
This should be fixed in newer versions.  Will release soon.
