### ISSUE TITLE
Cant access SD or HTTP Location

### ISSUE THREAD

**Issue by imPRAGMA** [digableinc/tinfoil#24]
pragma.nyx.feralhosting.com/
This is the directory
It cant load
In console it says "failed to open <folder>"
or
"failed to open file <full path>"
and it says it for tons of shit including dz.nro, "sxusb" 4 times among others

**Comment by blawar** [comment]
Yes, the only way it can pull in metadata is if it has [titleid] in the name.  We could read the info out of the NSP, but if we tried to do that everytime across the network, it would use lots of bandwidth and take a long time to start.  Its just much faster and cleaner to have it in the filename.

**Comment by blawar** [comment]
It also seems like you are using remote hosting on feral.  Current master (pushed last night) has an option to change the connection timeout.  I remember feral servers being slow to respond for some users.  This option may help you.
