### ISSUE TITLE
NSP's created with 4nxci sometimes fail to install

### ISSUE THREAD

**Issue by war3zlod3r** [digableinc/tinfoil#25]
I created several NSP's from xci's some install over tinfoil no problem the others sometimes give me an error that says "could not open cmnt nca" and "nca signature verification failed" any ideas why this would be?

**Comment by robbiered** [comment]
Tinfoil only allows proper NSPs signed by nintendo to install. This is to
prevent bad titles that have brick code in them to install. Since you are
making a hacked up NSP, the signatures wont match and thus wont install.
Please use a different program to install it.

**Comment by blawar** [comment]
We pushed a new version to master last night that will allow these NSP's to be installed if you turn on the option to "Install Unsigned Code".  4nxci conversions cannot be verified / confirmed they do not contain brick code, thats why they were previously blocked.  There was a release a malicious NSP's that bricked codes, that was to stop that.

**Comment by war3zlod3r** [comment]
Totally understandable keep doing the lords work!
