### ISSUE TITLE
[Suggestion] Add "Downloading" status to Queue

### ISSUE THREAD

**Issue by FM1337** [digableinc/tinfoil#26]
Rather than just showing the status as "Installing" even when something is still downloading, why not add a "Downloading" status and then switch to "Installing" when the downloading has finished

This is probably just me being a bit nitpicky and won't improve the performance at all, but it's just a suggestion.

**Comment by blawar** [comment]
Because downloading and installing are the same thing.  It is a stream install, the data is installed as its downloaded.
