### ISSUE TITLE
Master keys

### ISSUE THREAD

**Issue by Kptnfrakass** [digableinc/tinfoil#29]
Hello.
Since my last update of dz/tinfoil the homebrew is telling me that I don't have the master key 5 and 6?
Where can I get these please. 

Also, an option to turn sound to off and an other to auto grab the homebrew update.

Keep going on the good work!

**Comment by blawar** [comment]
Keys are copyrighted, and cannot be distributed.  Lockpick can help you dump your own keys:

https://github.com/shchmue/Lockpick
