### ISSUE TITLE
Switch crash when scaning NSP

### ISSUE THREAD

**Issue by Quesington** [digableinc/tinfoil#3]
FTP works perfectly and i can access from another PC and see the files but when i acces with the switch when it starts scanning for NSP it crash and force to restart the console

**Comment by Quesington** [comment]
nop keeps crashing the switch with an 2168-0002 error

**Comment by blawar** [comment]
Try latest master.

**Comment by Quesington** [comment]
Im gonna close the issue, my problem was the keys.txt , it was a bad dump

thanks for the help anyway
