### ISSUE TITLE
USB install causing freezes and crashing on Switch 6.2.0

### ISSUE THREAD

**Issue by deadair3210** [digableinc/tinfoil#31]
Whenever I try to install a nsp, about 2/3 of the time the Switch will either freeze or outright crash with a Fatal Error. The only thing I can see on the console for nut is usb_reap_async, and A device attached to the system is not functioning

**Comment by deadair3210** [comment]
Also, I'm getting usually timeout errors, which leads to the program (I assume) to try to recover, which usually leads to a Fatal Error

**Comment by blawar** [comment]
Do you have devices between the switch and the PC?  or is it wired directly from the PC to the switch?  I do not have a 6.2 switch to test on, however I heavily re-worked the USB code in the next update.  There is a good chance it might fix it.  Also, try a shorter and higher quality USB cable.  A bad connection can cause that.  Also use windows, ive heard of some weird issues with linux and mac (though some say it works fine for them).

**Comment by deadair3210** [comment]
In order of query -
Directly to PC, USB C to USB A
Cable is pretty short, not sure about quality. Never had devices drop off of the bus so I'm assuming its at least decent.
Using Windows 10

**Comment by fixx1983** [comment]
Same for me. I'm on 6.1.0 running ReiNX
