### ISSUE TITLE
Question: How can I see all files of a folder instead of the new ones only ?

### ISSUE THREAD

**Issue by 20Phoenix** [digableinc/tinfoil#32]
Hello.
Your tinfoil has a very nice GUI using the fine icons. 👍 
I use SX OS 2.3 with my 6.1.0 Switch. Files are located on USB HDD connected to the docking station in the folder sxusb:/nsp.
But I'm a little bit confused.

1.)
Under **New Games/DLC/Updates** appear really only new und not already installed files.
Why doesn't it show all my NSPs?
Where can I see **Games** instead of **New Games** only.
Couldn't you change it to **Games** and add a filter for new ones or all ones ?
I don't want to use the **File Browser** that doesn't use the nice icons!
I want to see all located file like at **New Games**.
2.)
In new game is listed correct in **New Games**.
But the associated update isn't shown in **New Updates**.
Why?
If I click on the new game icon, a list with base and update appears.
If I want to install the game I get an error, if I don't change "include lastest update" to yes.

**Comment by blawar** [comment]
new updates and new dlc only show updates and DLC for games you have installed.  You can press the right joystick to show all updates and dlc.  There is some quirkyness / bugs with it not showing all of the updates / DLC, howver I believe I have fixed this and will release an update soon.

**Comment by 20Phoenix** [comment]
Yeah, pressing the right joystick works fine, that's my solution.
I would prefer this overview with all files a default.
THANKS A LOT ^^

**Comment by 20Phoenix** [comment]
Now I notice something else:
I've two version of an update, the normal one and a patched one.
Name is the same, the patched one has patched added in the name.
But one one of these is listed :(
