### ISSUE TITLE
Request assistance language optimization

### ISSUE THREAD

**Issue by riggzh** [digableinc/tinfoil#36]
We can help translate non-English languages(zh-hans).
Please provide a location json

**Comment by blawar** [comment]
[zh.txt](https://github.com/digableinc/tinfoil/files/2683601/zh.txt)

please translate this file and return it to me :)  Thanks.

**Comment by blawar** [comment]
Thank you, your changes will be in the next version.  Sorry for the initial bad translations, we rely on the community to "correct" them for us as we only speak English :(
