### ISSUE TITLE
DZ Freezing

### ISSUE THREAD

**Issue by Goldkickerg70** [digableinc/tinfoil#37]
Okay so I don't know if this has to do with my computer or configuring nut correctly or what but I'm definitely having an issue. The first time I was using DZ I was trying to use doge but I couldn't get it to work properly so I decided to just use python directly on the directory of the nut folder in the doge folder, and it actually worked but I kinda had no idea what I did, DZ was able to connect to it and I was able to see all the nsps in it but now I wanted to use doge since it made it seem like doge can look at all the installed games on your switch. But shortly after using doge I tried connecting to it in DZ and it wouldn't work, so I tried to instead go back to directly using python on nut starting that server up instead but..... from that point on whenever I type my computer address into DZ it freezes for a while and then makes the sound of it backing out but nothing happens. After waiting for a long while however it ends up showing the file browser and it added the new server to it but opening it again leads to a long hang time until it eventually says timed out after 10000 milliseconds. Any ideas here? Oh and for nut I used the command "python nut.py --server" that is after using the scrape command first.

**Comment by blawar** [comment]
It sounds like it might be a firewall issue.  Are you still having an issue with the latest versions?

**Comment by Goldkickerg70** [comment]
Oh shoot, you can close this if you want lol, I fixed it like a month ago,
it was a firewall issue. Thanks anyways though!!
