### ISSUE TITLE
Cannot see updates using USB

### ISSUE THREAD

**Issue by fixx1983** [digableinc/tinfoil#38]
I'm using Tinfoil with USB. I've a NSP folder with three subfolders GAMES, DLC and UPDATES.

I can see the first and the second, but the third one doesn't show anything neither for the already installed games. If I move "Install with latest update" on ON, it works. But I'm sure some of my already installed games are outdated.

**Comment by blawar** [comment]
try the latest version of nut.

**Comment by fixx1983** [comment]
I'm already on 0.99 sadly

**Comment by blawar** [comment]
I meant update Nut, not Tinfoil

**Comment by fixx1983** [comment]
It works, thanks
