### ISSUE TITLE
Can't install game XCI2NSP

### ISSUE THREAD

**Issue by imedox** [digableinc/tinfoil#44]
hello,
Can't install converted game from XCI2NSP it say "NCA signature verification failed"  with hold DZ it work , the new tinfoil v1.0 have this issue

**Comment by shyim** [comment]
Disable signature checking, its the first option on the install page.
The code is the konami code :)

**Comment by blawar** [comment]
thank you for answering that question for op @shyim , I have been busy during the holidays.  Sounds like his issue is resolved, closing.
