### ISSUE TITLE
FTP Pasv Mode support

### ISSUE THREAD

**Issue by cattivik66** [digableinc/tinfoil#46]
It would be nice to implement the support to PASV mode for the ftp client.
This allows to open only a few number of ports if anyone want to host a public ftp server (instead of open all ports from 1025 to 65535).

Currently Tinfoil connects using active connections, that means that the client tells to the server the port to use. Using PASV mode makes the server assign a port to the client for the transfer, and so reduce the opened ports to something like 3-6 ports.

**Comment by blawar** [comment]
I only forward port 21 through the NAT and it works.  Which FTP server are you using?
