### ISSUE TITLE
New Updates or dlc detections

### ISSUE THREAD

**Issue by Kptnfrakass** [digableinc/tinfoil#5]
Hello,
Great work but some dlc or update doesn't seems to be detected. 

Ex : Diablo 3 language pack. 
Into the breach update

The installation with the file browser doesn't work all the time. Many downloads don't starts when the file is selected. 

The link between dlc/UPD and the base game is only on the titlekey? Right?

Tks a lot anyway.

**Comment by blawar** [comment]
The link between DLC / UPD is the title id, not the key.

Have you tried pressing Y on the DLC / Updates screen?

**Comment by Kptnfrakass** [comment]
On the update screen the Y button give me a white screen only. 
On dlc it shows me the installed dlc.
I just renamed the files. It seems to be case sensitive. 
Just putting the title ID in caps resolved the issue
