### ISSUE TITLE
failed to open key

### ISSUE THREAD

**Issue by MikeyTaylor1991** [digableinc/tinfoil#50]
I have an issue when trying to delete application record of Super Smash Bros Ultimate. It tells me that it "Failed to remove record" and I'm not sure why. Could it be to do with the fact it hasn't found my keys.txt? 

keys.txt does exist in the switch/tinfoil folder so I'm not sure why it didn't detect them either to be honest.

**Comment by lildrill** [comment]
I have got the same issue here, i do also have the keys.txt with the necessary keys in it.

**Comment by MikeyTaylor1991** [comment]
Strange. I followed a guide to get keys.txt a different way involving Python from GBAtemp.net too, but I've never had much luck with Python and it's fair to say, haven't managed to get it working this time either.

**Comment by blawar** [comment]
is the keys.txt in /switch/tinfoil/keys.txt?  You guys should probably just google for switch keys.txt to get it.

**Comment by Lee-Fixter** [comment]
Same issue here too 
![image](https://user-images.githubusercontent.com/47419089/53304626-57f96c00-386f-11e9-8f78-7394a004f3de.png)

**Comment by MikeyTaylor1991** [comment]
Yes, the file is located there. I thought that all keys were different, no?

**Comment by blawar** [comment]
all of the keys needed in keys.txt are the same for every console.
