### ISSUE TITLE
how has this program gotten worse with every release?

### ISSUE THREAD

**Issue by gravysamich** [digableinc/tinfoil#51]
i am genuinely asking. it seems that with every release, this program has gotten slower and less functional. 

i have been using this since it was called DZ. to this day i still think that versions was the most usable version.

 this isn't hyperbole either. i finally decided to update from .99 to 1.0 today. i already wasn't happy with the update to .99 as even then it seemed slower. i still have both versions installed. .99 is so much smoother. it loads faster and in general seems less janky. 

 it seems like you have put too much focus on the UI when you should be cleaning up your code. the user experience has just steadily gotten worse. some bugs may have been fixed, but it all just doesn't matter if the program itself isn't easy to use.

i am one of the few people out there that prefer this program to the other tinfoil so it saddens me to see it in this state. for now i am just going to continue using .99 but i don't know how much longer i can justify that.

**Comment by blawar** [comment]
not an issue.

**Comment by gravysamich** [comment]
it may not be a bug, but it most certainly is an issue. 

are you planning to just ignore this criticism? 

you already don't have the best image in the community. i don't think ignoring the few people who use your apps is a good thing. 

if i have to bring up a genuine problem for you to take this seriously, why does 1.0 take significantly longer to load than .99? it also seems to crash and freeze when installing. i cant even look at the ques without it freezing up. this wasn't an issue in previous iterations.
