### ISSUE TITLE
Feature request: save list of installed games and their update version

### ISSUE THREAD

**Issue by ShidaPenns** [digableinc/tinfoil#53]
Would this be possible? I have a 400 GB micro SD so I have a lot of installed games. It would make it easier to find the latest update for them if I could open a text file with this info.

**Comment by blawar** [comment]
it already does this when you connect to a network nut server.

**Comment by ShidaPenns** [comment]
Hmm, okay, I'll look into that then. Thanks. :)

**Comment by ShidaPenns** [comment]
Hmm, how do I actually do that? I'm probably missing something but I can't see how to use it to save a list of games that are already installed, with currently installed update version.

**Comment by blawar** [comment]
login to the nut server via network, then look in nut's switch folder.
