### ISSUE TITLE
Feature Request: Download images from nut instead cdn

### ISSUE THREAD

**Issue by 2g4y1** [digableinc/tinfoil#54]
Hi, i use 90dns to block all connections to the nintendo servers. So the cdn is not reachable for my switch. So my suggestion is to load the images from the nut server if available instead of the cdn. I see a lot of cdn unreachable messages in the console tab. would that be possible?

i use Tinfoil Version 1.1 (latest commit) on AMS 0.8.4 with latest nut realease

Edit: i mean the picture in the info hen i press Y at a game that isn't installed

**Comment by blawar** [comment]
use incognito, then disable 90dns and download the images:

https://github.com/blawar/incognito
