### ISSUE TITLE
this just plain doesn't work 95% of the time. 

### ISSUE THREAD

**Issue by gravysamich** [digableinc/tinfoil#6]
i had been using an old DZ to network install my nsp for a while now. i finally decided to update my firmware to 6.1. suddenly DZ didn't work any more. no big deal, i figured i would just update and everything would be fine. i saw it moved here. i downloaded and installed this.

it didn't work. i thought my ftp settings from dz would work. the file browser shows the location, but no files show up. i figured i was doing something wrong.

i restarted my switch a few times thinking maybe that would help. after 4 or 5 resets, my files showed up! hooray! it isn't something im doing then. i was able to install a game. i closed the program to test the game. when i reopened this, my files went back to not showing up. i haven't got the program to work since.

if it is something i am doing, why would i see my files the one time.

when i look at the console, i get the readout 

failed to open file sdmc://switch/dz/db/titles.US.en.json
network error: Connection timed out after 10000 milliseconds
failed to open sxusb

**Comment by blawar** [comment]
post your locations.conf , censor any passwords or sensitive info.  also, you should upload db/titles.US.en.json to your as card

**Comment by gravysamich** [comment]
i managed to fix it. i didn't realize that i needed to specify a port at the end of my host ip. i noticed that the port it was trying to connect to seemed to be different every time i tried to connect. you should change the ftp example to reflect this.

**Comment by blawar** [comment]
i believe that was fixed in today’s commit.  either way i’m glad you have it working :)

**Comment by gravysamich** [comment]
me too as this program makes things so much easier!
