### ISSUE TITLE
Kosmos nag when chainloading fusee primary

### ISSUE THREAD

**Issue by megarobohobo** [digableinc/tinfoil#66]
I don't want to remove hekate. If I'm chainloading fusee-primary, why do I have to remove hekate?

**Comment by Elionna** [comment]
agreed, confused as to why this is enforced when I am using atmosphere and not kosmos, all the later versions of tinfoil are unusable right now because of this block.

**Comment by megarobohobo** [comment]
Switched to goldleaf, nm
