### ISSUE TITLE
Failed to read NSP metadata

### ISSUE THREAD

**Issue by namoi76** [digableinc/tinfoil#68]
I have this issue trying to install Diablo 3 NSP using USB nut server (install fine with Goldleaf) where i got this error followed by "Unknown NCA magic (decryption failed ?):2246578310".

Under SX OS 2.6.2 (emunand FW 7.0.1) and also SX OS 7.0.1 (emunand FW 8.0.1).
I tried to enable the unsigned install option in tinfoil to no avail and as I said the nsp install fine under Goldleaf/Goldtree so it is not corrupted.

**Comment by esReh** [comment]
i had the same issue with Diablo 3. it installed well on 7.01, but failed now on 8.1.0 with most recent atmosphere.
However I was able to solve the issue by installing the nsp over usbfs:/ instead of usb:/ 
it also did not work to install it when listed under new games.

**Comment by blawar** [comment]
this was fixed with the latest 2.20 version of tinfoil
