### ISSUE TITLE
pls 4god sake take FOLDERs Back, Blawar. Pictures high quality for low size and others...

### ISSUE THREAD

**Issue by obikuni** [digableinc/tinfoil#7]
The old Folder's method that you have used in the DZ it's much better... I still have the backups when they were like 2Mb files.. please take off this "new games" to that us can put the name at the folder that we want and... to show always in order alphabetical. 

And one more thing, the discord was take down and I miss you kkkk...
pls, stop doing big shitz and let this amazing app keep some things that the other one DZ did best.

ohhhh, the new "layout" showing prints is really good. but the quality is really high for the size showed... ??? will have the option to fullscreen the image on the future ?

by Obikuni

**Comment by ThatNerdyPikachu** [comment]
what the

**Comment by blawar** [comment]
You can use the file browser for this functionality.
