### ISSUE TITLE
"Not enough memory to run" (Low mem) warning in applet mode

### ISSUE THREAD

**Issue by timothyrobb** [digableinc/tinfoil#83]
**EDIT:**

**This only appears to happen in the new Applet mode.**

If booting HBMenu from an application (Holding down R when booting any other non-gallery title), it seems to work fine.

---

Hey there, just updated from 4.10 (non-beta) to 5.00, but I'm getting a memory warning whenever I try to open it up, even right after a fresh reboot.

After dismissing the error, I just get a blank app without any content

Here's a photo:

![IMG_1741](https://user-images.githubusercontent.com/1174168/66278220-675f8e00-e903-11e9-8774-b765bfb18482.JPG)

**Comment by blawar** [comment]
Reconfigure atmosphere to not reserve 128MB of ram, or use the hbl.nsp that is included in the tinfoil zip file and reboot.
