### ISSUE TITLE
HTTP servers (Apache and NGINX) index shows 0.0

### ISSUE THREAD

**Issue by bjgamer2019** [digableinc/tinfoil#91]
Local HTTP servers don't were being correctly parsed by Tinfoil. Shows files with 0.0 size. If locally accessed by HTTP browsers, shows the size correctly.

Any tips? Thanks.

**Comment by blawar** [comment]
that’s because there is no standard way to report sizes by web servers, it’s just all html in any format, sometimes javascript.  not trying to parse that.

**Comment by bjgamer2019** [comment]
Any way to force that (configuration maybe), to show correctly. Thanks for your fast answer. I will investigate more.

**Comment by blawar** [comment]
use a script to create a json index
